// <auto-generated />
namespace FIT5032AssignmentV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProviderCourseModel5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProviderCourseModel5));
        
        string IMigrationMetadata.Id
        {
            get { return "202010240440414_ProviderCourseModel5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
