// <auto-generated />
namespace FIT5032_W04_CodeFirst_Second_Edition_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280903411_StudentModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
